"""Snapshot tests for RayCodeGen, SlurmCodeGen and LsfCodeGen code generation.

These tests validate that the code generators produce consistent output for
various configurations. The expected outputs are stored in:
- testdata/ray_codegen/*.py
- testdata/slurm_codegen/*.py
- testdata/lsf_codegen/*.py

To update snapshots when intentional changes are made:
    UPDATE_SNAPSHOT=1 pytest tests/unit_tests/test_sky/backends/test_task_codegen.py
"""
import os
from pathlib import Path
import subprocess

import pytest

from sky.backends import task_codegen
from sky.provision.slurm import utils as slurm_utils

TESTDATA_DIR = Path(__file__).parent / 'testdata' / 'ray_codegen'
SLURM_TESTDATA_DIR = Path(__file__).parent / 'testdata' / 'slurm_codegen'
LSF_TESTDATA_DIR = Path(__file__).parent / 'testdata' / 'lsf_codegen'


def assert_codegen_matches_snapshot(test_name: str,
                                    generated_code: str,
                                    testdata_dir: Path = TESTDATA_DIR) -> None:
    """Compare generated code against snapshot file.

    Args:
        test_name: Name of the test (used to find snapshot file)
        generated_code: The code generated by RayCodeGen or SlurmCodeGen
        testdata_dir: Directory containing test snapshots (default: ray_codegen)

    If UPDATE_SNAPSHOT=1 env var is set, updates the snapshot file instead
    of comparing.
    """
    snapshot_path = testdata_dir / f'{test_name}.py'

    if os.environ.get('UPDATE_SNAPSHOT') == '1':
        # Update snapshot
        snapshot_path.parent.mkdir(parents=True, exist_ok=True)
        snapshot_path.write_text(generated_code)
        print(f'Updated snapshot: {snapshot_path}')
        return

    # Read expected snapshot
    if not snapshot_path.exists():
        pytest.fail(f'Snapshot file not found: {snapshot_path}\n'
                    f'Run with UPDATE_SNAPSHOT=1 to create it.')

    expected = snapshot_path.read_text()

    # Compare
    if generated_code != expected:
        # Show helpful diff message
        import difflib
        diff = difflib.unified_diff(
            expected.splitlines(keepends=True),
            generated_code.splitlines(keepends=True),
            fromfile=f'{test_name}.py (expected)',
            tofile=f'{test_name}.py (actual)',
        )
        diff_text = ''.join(diff)
        pytest.fail(
            f'Generated code does not match snapshot: {snapshot_path}\n\n'
            f'Diff:\n{diff_text}\n\n'
            f'Run with UPDATE_SNAPSHOT=1 to update the snapshot.')


def test_single_node_with_gpu():
    """Test single-node GPU job with setup commands.

    Mirrors usage in _execute_task_one_node() with GPU and setup.
    """
    codegen = task_codegen.RayCodeGen()
    codegen.add_prologue(job_id=2)

    resources_dict = {'CPU': 4.0, 'GPU': 1.0}
    task_env_vars = {
        'SKYPILOT_TASK_ID': 'sky-2024-11-17-00-00-00-000001-cluster-2',
        'MODEL_NAME': 'resnet50',
    }

    codegen.add_setup(
        1,
        resources_dict=resources_dict,
        stable_cluster_internal_ips=['10.0.0.1'],
        env_vars=task_env_vars,
        log_dir='/sky/logs',
        setup_cmd='pip install torch',
    )

    # Single node: no gang_scheduling_id passed
    codegen.add_task(
        1,
        bash_script='python train.py',
        task_name='train_task',
        resources_dict={
            'CPU': 4.0,
            'GPU': 1.0
        },
        log_dir='/sky/logs/tasks',
        env_vars=task_env_vars,
    )

    codegen.add_epilogue()

    result = codegen.build()
    assert_codegen_matches_snapshot('single_node_with_gpu', result)


def test_multi_node_2nodes():
    """Test multi-node job (2 nodes).

    Mirrors usage in _execute_task_n_nodes() for basic multi-node setup.
    """
    codegen = task_codegen.RayCodeGen()
    codegen.add_prologue(job_id=3)

    num_nodes = 2
    resources_dict = {'CPU': 2.0}
    task_env_vars = {
        'SKYPILOT_TASK_ID': 'sky-2024-11-17-00-00-00-000002-cluster-3',
    }

    codegen.add_setup(
        num_nodes,
        resources_dict=resources_dict,
        stable_cluster_internal_ips=['10.0.0.1', '10.0.0.2'],
        env_vars=task_env_vars,
        log_dir='/sky/logs',
        setup_cmd=None,
    )

    codegen.add_task(
        num_nodes,
        bash_script='echo "Running on node $SKYPILOT_NODE_RANK"',
        task_name='distributed_task',
        resources_dict={'CPU': 2.0},
        log_dir='/sky/logs/tasks',
        env_vars=task_env_vars,
    )

    codegen.add_epilogue()

    result = codegen.build()
    assert_codegen_matches_snapshot('multi_node_2nodes', result)


def test_slurm_single_node_with_gpu():
    """Test single-node GPU job with setup commands on Slurm.

    Mirrors test_single_node_with_gpu() but for SlurmCodeGen.
    """
    codegen = task_codegen.SlurmCodeGen(
        slurm_job_id='12345',
        container_name=None,
    )
    codegen.add_prologue(job_id=2)

    resources_dict = {'CPU': 4.0, 'GPU': 1.0}
    task_env_vars = {
        'SKYPILOT_TASK_ID': 'sky-2024-11-17-00-00-00-000001-cluster-2',
        'MODEL_NAME': 'resnet50',
    }

    codegen.add_setup(
        1,
        resources_dict=resources_dict,
        stable_cluster_internal_ips=['10.0.0.1'],
        env_vars=task_env_vars,
        log_dir='/sky/logs',
        setup_cmd='pip install torch',
    )

    codegen.add_task(
        1,
        bash_script='python train.py',
        task_name='train_task',
        resources_dict={
            'CPU': 4.0,
            'GPU': 1.0
        },
        log_dir='/sky/logs/tasks',
        env_vars=task_env_vars,
    )

    codegen.add_epilogue()

    result = codegen.build()
    assert_codegen_matches_snapshot('slurm_single_node_with_gpu',
                                    result,
                                    testdata_dir=SLURM_TESTDATA_DIR)


def test_slurm_codegen_with_container():
    codegen = task_codegen.SlurmCodeGen(
        slurm_job_id='12345',
        container_name=slurm_utils.pyxis_container_name('test-cluster'),
    )
    codegen.add_prologue(job_id=2)

    resources_dict = {'CPU': 2.0}
    task_env_vars = {}

    codegen.add_setup(
        1,
        resources_dict=resources_dict,
        stable_cluster_internal_ips=['10.0.0.1'],
        env_vars=task_env_vars,
        log_dir='/sky/logs',
        setup_cmd=None,
    )

    codegen.add_task(
        1,
        bash_script='echo hello',
        task_name='hello',
        resources_dict={'CPU': 1.0},
        log_dir='/sky/logs/tasks',
        env_vars=task_env_vars,
    )

    codegen.add_epilogue()

    result = codegen.build()
    assert_codegen_matches_snapshot('slurm_codegen_with_container',
                                    result,
                                    testdata_dir=SLURM_TESTDATA_DIR)


class TestRcloneFlushScript:
    """Unit tests for the rclone flush script output format."""

    def test_flush_script_contains_elapsed_time(self):
        """Test that flush script reports elapsed time in status messages."""
        codegen = task_codegen.RayCodeGen()
        flush_script = codegen.get_rclone_flush_script()

        # Should track and report elapsed time
        assert 'FLUSH_START_TIME=$(date +%s)' in flush_script
        assert 'ELAPSED=$(($(date +%s) - FLUSH_START_TIME))' in flush_script
        assert '${ELAPSED}s' in flush_script

    def test_flush_script_shows_cache_status(self):
        """Test that flush script extracts and shows vfs cache status."""
        codegen = task_codegen.RayCodeGen()
        flush_script = codegen.get_rclone_flush_script()

        # Should extract cache status from log
        assert 'CACHE_STATUS=' in flush_script
        assert "vfs cache: cleaned:" in flush_script
        assert '[${CACHE_STATUS}]' in flush_script

    def test_flush_script_shows_uploading_files(self):
        """Test that flush script shows files currently being uploaded."""
        codegen = task_codegen.RayCodeGen()
        flush_script = codegen.get_rclone_flush_script()

        # Should extract uploading files from log
        assert 'UPLOADING_FILES=' in flush_script
        assert 'queuing for upload' in flush_script
        assert 'uploading: ${UPLOADING_FILES}' in flush_script
        # Should properly handle comma separation (no trailing comma)
        assert "sed 's/,$//'" in flush_script

    def test_flush_script_has_fallback_output(self):
        """Test that flush script falls back to last log line if parsing fails."""
        codegen = task_codegen.RayCodeGen()
        flush_script = codegen.get_rclone_flush_script()

        # Should have fallback to last line
        assert 'LAST_LINE=' in flush_script
        assert 'Fallback' in flush_script
        # Should have bare elapsed time as final fallback
        assert 'cached mount is still uploading (elapsed: ${ELAPSED}s)"' in flush_script

    def test_flush_script_shows_completion_time(self):
        """Test that flush script shows total time when upload completes."""
        codegen = task_codegen.RayCodeGen()
        flush_script = codegen.get_rclone_flush_script()

        # Should report total flush time on completion
        assert 'TOTAL_FLUSH_TIME=$(($(date +%s) - FLUSH_START_TIME))' in flush_script
        assert 'cached mount upload complete (took ${TOTAL_FLUSH_TIME}s)' in flush_script

    def test_flush_script_output_message_formats(self):
        """Test that all output message variants are present."""
        codegen = task_codegen.RayCodeGen()
        flush_script = codegen.get_rclone_flush_script()

        # Format 1: cache status + uploading files
        assert (
            'cached mount is still uploading (elapsed: ${ELAPSED}s) '
            '[${CACHE_STATUS}] uploading: ${UPLOADING_FILES}') in flush_script

        # Format 2: cache status only
        assert ('cached mount is still uploading (elapsed: ${ELAPSED}s) '
                '[${CACHE_STATUS}]"') in flush_script

        # Format 3: last line fallback
        assert ('cached mount is still uploading (elapsed: ${ELAPSED}s) '
                '${LAST_LINE}"') in flush_script

        # Format 4: bare elapsed time (final fallback)
        assert 'cached mount is still uploading (elapsed: ${ELAPSED}s)"' in flush_script

    def test_slurm_flush_script_same_as_ray(self):
        """Test that SlurmCodeGen uses the same flush script as RayCodeGen."""
        ray_codegen = task_codegen.RayCodeGen()
        slurm_codegen = task_codegen.SlurmCodeGen(
            slurm_job_id='12345',
            container_name=None,
        )

        ray_script = ray_codegen.get_rclone_flush_script()
        slurm_script = slurm_codegen.get_rclone_flush_script()

        assert ray_script == slurm_script

    @pytest.mark.parametrize('cmd,expected_code', [
        ('true', 0),
        ('false', 1),
        ('bash -c "exit 0"', 0),
        ('bash -c "exit 1"', 1),
        ('bash -c "exit 2"', 2),
        ('python3 -c "import sys; sys.exit(0)"', 0),
        ('python3 -c "import sys; sys.exit(1)"', 1),
    ])
    def test_flush_script_preserves_user_exit_code(self, cmd, expected_code):
        """Test that rclone flush script preserves the user command's
        exit code."""
        script = task_codegen.TaskCodeGen.build_task_bash_script(cmd)
        result = subprocess.run(['bash', '-c', script],
                                capture_output=True,
                                check=False)
        assert result.returncode == expected_code


# ─── LsfCodeGen ──────────────────────────────────────────────────────────────
#
# These snapshots are a baseline, not an endorsement: LsfCodeGen currently
# hardcodes single-node values in every branch, so test_lsf_multi_node_2nodes
# below records generated code that is *wrong* for a 2-node job. Freezing it
# first means the fix shows up as a reviewable diff rather than a wall of new
# code. See the M1 commit plan (A1) for the sequence.

_LSF_HOME = '/proj/granite-build/g4os/skypilot/sky-gold-kd-abc123'


def _lsf_task_env_vars():
    return {
        'SKYPILOT_TASK_ID': 'sky-2024-11-17-00-00-00-000001-cluster-2',
        'MODEL_NAME': 'granite-4.1-3b-base',
    }


def test_lsf_single_node_dispatch():
    """Single-node LSF job dispatched into a container via the shared FS.

    Mirrors test_slurm_single_node_with_gpu() but for LsfCodeGen, whose
    compute-node hop is the shared-filesystem dispatcher rather than srun.
    """
    codegen = task_codegen.LsfCodeGen(
        dispatch_root=_LSF_HOME + '/.sky/dispatch',
        topology_dir=_LSF_HOME + '/.sky/topology',
        nodes=['p1-r08-n4'],
        node_ips=['10.0.0.1'],
    )
    codegen.add_prologue(job_id=2)

    resources_dict = {'CPU': 4.0, 'GPU': 8.0}
    task_env_vars = _lsf_task_env_vars()

    codegen.add_setup(
        1,
        resources_dict=resources_dict,
        stable_cluster_internal_ips=['10.0.0.1'],
        env_vars=task_env_vars,
        log_dir='/sky/logs',
        setup_cmd='echo no-op setup',
    )

    codegen.add_task(
        1,
        bash_script='accelerate launch gold/gold.py',
        task_name='gold_distill',
        resources_dict=resources_dict,
        log_dir='/sky/logs/tasks',
        env_vars=task_env_vars,
    )

    codegen.add_epilogue()

    result = codegen.build()
    assert_codegen_matches_snapshot('lsf_single_node_dispatch',
                                    result,
                                    testdata_dir=LSF_TESTDATA_DIR)


def test_lsf_multi_node_2nodes():
    """Two-node LSF job — the GOLD-distillation shape.

    Records today's broken output so the multi-node fix is a visible diff. The
    snapshot is expected to contain SKYPILOT_NUM_NODES=1, SKYPILOT_NODE_RANK=0,
    SKYPILOT_NODE_IPS='127.0.0.1', and a single cmd_<seq>.sh write — see the
    assertions in test_lsf_multi_node_is_currently_single_node below, which state
    the bug directly rather than leaving it implicit in the golden file.
    """
    codegen = task_codegen.LsfCodeGen(
        dispatch_root=_LSF_HOME + '/.sky/dispatch',
        topology_dir=_LSF_HOME + '/.sky/topology',
        nodes=['p1-r08-n4', 'p1-r08-n5'],
        node_ips=['10.0.0.1', '10.0.0.2'],
    )
    codegen.add_prologue(job_id=2)

    resources_dict = {'CPU': 4.0, 'GPU': 8.0}
    task_env_vars = _lsf_task_env_vars()

    codegen.add_setup(
        2,
        resources_dict=resources_dict,
        stable_cluster_internal_ips=['10.0.0.1', '10.0.0.2'],
        env_vars=task_env_vars,
        log_dir='/sky/logs',
        setup_cmd='echo no-op setup',
    )

    codegen.add_task(
        2,
        bash_script='accelerate launch gold/gold.py',
        task_name='gold_distill',
        resources_dict=resources_dict,
        log_dir='/sky/logs/tasks',
        env_vars=task_env_vars,
    )

    codegen.add_epilogue()

    result = codegen.build()
    assert_codegen_matches_snapshot('lsf_multi_node_2nodes',
                                    result,
                                    testdata_dir=LSF_TESTDATA_DIR)


def test_lsf_multi_node_bare_metal():
    """Two-node LSF job with no dispatch_root at all — the login-node fallback.

    This is no longer what a bare-metal cluster produces: the provisioner now runs
    a dispatcher on every host without enroot, and the backend supplies
    dispatch_root regardless of container image, so bare-metal dispatches to the
    allocation (see test_lsf_bare_metal_with_dispatch_uses_the_executor). What
    remains on this path is a cluster provisioned before that existed, where
    executing on the login node is the only option left.
    """
    codegen = task_codegen.LsfCodeGen()
    codegen.add_prologue(job_id=2)

    resources_dict = {'CPU': 4.0, 'GPU': 0.0}
    task_env_vars = _lsf_task_env_vars()

    codegen.add_setup(
        2,
        resources_dict=resources_dict,
        stable_cluster_internal_ips=['10.0.0.1', '10.0.0.2'],
        env_vars=task_env_vars,
        log_dir='/sky/logs',
        setup_cmd=None,
    )

    codegen.add_task(
        2,
        bash_script='hostname',
        task_name='topology_probe',
        resources_dict=resources_dict,
        log_dir='/sky/logs/tasks',
        env_vars=task_env_vars,
    )

    codegen.add_epilogue()

    result = codegen.build()
    assert_codegen_matches_snapshot('lsf_multi_node_bare_metal',
                                    result,
                                    testdata_dir=LSF_TESTDATA_DIR)


def test_lsf_multi_node_delegates_per_node_env_to_the_executor():
    """State the multi-node contract as assertions, not just a golden file.

    A reviewer reading a large snapshot diff will not reliably notice that
    SKYPILOT_NUM_NODES stopped being pinned to 1. These assertions replace the
    ones that recorded the defect: the generated code must no longer hardcode
    rank 0, a single node, or loopback as the peer list, and must hand the
    per-node work to the executor along with every allocated host.
    """
    codegen = task_codegen.LsfCodeGen(
        dispatch_root='/tmp/dispatch',
        topology_dir='/tmp/topology',
        nodes=['host1', 'host2'],
        node_ips=['10.0.0.1', '10.0.0.2'],
    )
    codegen.add_prologue(job_id=2)
    codegen.add_setup(
        2,
        resources_dict={'CPU': 4.0},
        stable_cluster_internal_ips=['10.0.0.1', '10.0.0.2'],
        env_vars={},
        log_dir='/sky/logs',
        setup_cmd='true',
    )
    codegen.add_task(
        2,
        bash_script='hostname',
        task_name='probe',
        resources_dict={'CPU': 4.0},
        log_dir='/sky/logs/tasks',
        env_vars={},
    )
    codegen.add_epilogue()
    code = codegen.build()

    # No per-node value is decided here any more; the executor sets them once it
    # knows each node's rank.
    assert "sky_env_vars_dict['SKYPILOT_NODE_RANK'] = 0" not in code
    assert "sky_env_vars_dict['SKYPILOT_NODE_IPS'] = '127.0.0.1'" not in code
    assert "'SKYPILOT_NUM_NODES'] = 1" not in code

    # Both hosts reach the executor, for the task and for setup.
    assert code.count('lsf_executor.run_on_all_nodes(') == 2
    assert "nodes=['host1', 'host2']" in code
    assert "node_ips=['10.0.0.1', '10.0.0.2']" in code
    assert "topology_dir='/tmp/topology'" in code
    assert 'is_setup=True' in code
    assert 'is_setup=False' in code

    # Setup no longer writes to a fixed 'setup' sequence name, which N nodes
    # would have contended for.
    assert "seq = 'setup'" not in code


def test_lsf_bare_metal_with_dispatch_uses_the_executor():
    """A bare-metal cluster dispatches to its nodes, same as a containerized one.

    Before this, the fan-out and dispatcher were emitted only inside the enroot
    block, so a bare-metal multi-node allocation ran the task once on the login
    node and left every allocated host idle. The codegen difference is that
    dispatch_root is now populated whether or not there is a container image.
    """
    codegen = task_codegen.LsfCodeGen(
        dispatch_root='/proj/builds/cluster/.sky/dispatch',
        topology_dir='/proj/builds/cluster/.sky/topology',
        nodes=['host1', 'host2'],
        node_ips=['10.0.0.1', '10.0.0.2'],
    )
    codegen.add_prologue(job_id=2)
    codegen.add_setup(
        2,
        resources_dict={'CPU': 4.0},
        stable_cluster_internal_ips=['10.0.0.1', '10.0.0.2'],
        env_vars={},
        log_dir='/sky/logs',
        setup_cmd=None,
    )
    codegen.add_task(
        2,
        bash_script='hostname',
        task_name='probe',
        resources_dict={'CPU': 4.0},
        log_dir='/sky/logs/tasks',
        env_vars={},
    )
    codegen.add_epilogue()
    code = codegen.build()

    assert 'lsf_executor.run_on_all_nodes(' in code
    assert "nodes=['host1', 'host2']" in code
    # The login-node path must not be taken when the nodes are reachable. Assert
    # on the CALL, not the name: the helper's definition is inlined into every
    # prologue whether or not this branch uses it.
    assert 'result = run_bash_command_with_log_and_return_pid(' not in code
    assert "sky_env_vars_dict['SKYPILOT_NODE_RANK'] = 0" not in code
